openapi: 3.0.1
info:
  title: Sonatype Lifecycle Public REST Advanced Search Config SAML API
  version: 1.201.0-02
  description: Use the Advanced Search REST API to perform searches on Lifecycle application scan reports.
security:
- BasicAuth: []
  BearerAuth: []
tags:
- description: Use this REST API to manage the SAML configuration for IQ Server.
  name: Config SAML
paths:
  /api/v2/config/saml:
    delete:
      description: 'Use this method to delete the SAML configuration.


        Permissions required: Edit System Configuration and Users.'
      operationId: deleteSamlConfiguration
      responses:
        '204':
          description: Successfully deleted the SAML configuration.
        '404':
          description: No SAML configuration found.
      tags:
      - Config SAML
    get:
      description: 'Use this method to inspect the SAML configuration.


        Permissions required: Edit System Configuration and Users'
      operationId: getSamlConfiguration
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiSamlConfigurationResponseDTO'
          description: The response contains:<ul><li>`identityProviderName` the name of the Identity Provider that is displayed on the login page when SAML is configured.</li><li>`entityId` is the URI that IQ Server uses to identify itself in requests to the SSOservice.</li><li>`firstNameAttribute` is the SAML attribute that IQ Server extracts from the login response of the identity provider and uses as the user's first name.</li><li>`lastNameAttribute` is the SAML attribute that IQ Server extracts from the login response of the identity provider and uses as the user's last name.</li><li>`emailAttributeName` is the SAML attribute that IQ Server extracts from the login response of the identity provider to determine the user's email address.</li><li>`usernameAttributeName` is the SAML attribute that IQ Server extracts from the login response of the identity provider to determine the username or id.</li><li>`groupAttributeName` is the SAML attribute that IQ Server extracts from the login response of the identity provider to determine the groups the user belongs to.</li><li>`validateResponseSignature` indicates whether the SAML responses from the identity provider  are cryptographically signed. A `null` value indicates that this setting is derived from the SAML metadata from the identity provider performing signature validation if a signing key (`KeyDescriptor`) is included.<li>`validateAssertionSignature` indicates whether the SAML assertions from the identity provider  are cryptographically signed. A `null` value indicates that this setting is derived from  the SAML metadata from the identity provider performing signature validation if a signing key (`KeyDescriptor`) is included.</li><li>`identityProviderMetadataXml` is the metadata of the identity provider.</li></ul>
        '404':
          description: SAML is not configured.
      tags:
      - Config SAML
    put:
      description: 'Use this method to enable SSO using SAML. This request uses the content type multipart/form-data to transmit the configuration to IQ Server.


        Permissions required: Edit System Configuration and Users'
      operationId: insertOrUpdateSamlConfiguration
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                identityProviderXml:
                  description: Enter the SAML metadata XML of your IdP. Refer to the IdP documentation to obtain this metadata.
                  type: string
                samlConfiguration:
                  $ref: '#/components/schemas/ApiSamlConfigurationDTO'
              type: object
      responses:
        '204':
          description: Configuration successful.
        '400':
          description: Invalid configuration.
      tags:
      - Config SAML
  /api/v2/config/saml/metadata:
    get:
      description: 'Use this method to retrieve IQ Server''s metadata service provider descriptor.


        Permissions required: Edit System Configuration and Users'
      operationId: getMetadata
      responses:
        '200':
          content:
            application/xml:
              schema:
                type: string
          description: The IQ Server's metadata service provider descriptor in XML format.
        '404':
          description: SAML is not configured.
      tags:
      - Config SAML
components:
  schemas:
    ApiSamlConfigurationResponseDTO:
      properties:
        emailAttributeName:
          type: string
        entityId:
          type: string
        firstNameAttributeName:
          type: string
        groupsAttributeName:
          type: string
        identityProviderMetadataXml:
          type: string
        identityProviderName:
          type: string
        lastNameAttributeName:
          type: string
        usernameAttributeName:
          type: string
        validateAssertionSignature:
          type: boolean
        validateResponseSignature:
          type: boolean
      type: object
    ApiSamlConfigurationDTO:
      description: Enter the SAML configuration<ul><li>`identityProviderName` the name of the Identity Provider that is displayed on the login page when SAML is configured.</li><li>`entityId` is the URI that IQ Server uses to identify itself in requests to the SSOservice.</li><li>`firstNameAttribute` is the SAML attribute that IQ Server extracts from the login response of the identity provider and uses as the user's first name.</li><li>`lastNameAttribute` is the SAML attribute that IQ Server extracts from the login response of the identity provider and uses as the user's last name.</li><li>`emailAttributeName` is the SAML attribute that IQ Server extracts from the login response of the identity provider to determine the user's email address.</li><li>`usernameAttributeName` is the SAML attribute that IQ Server extracts from the login response of the identity provider to determine the username or id.</li><li>`groupAttributeName` is the SAML attribute that IQ Server extracts from the login response of the identity provider to determine the groups the user belongs to.</li><li>`validateResponseSignature` indicates whether the SAML responses from the identity provider  are cryptographically signed. A `null` value indicates that this setting is derived from the SAML metadata from the identity provider performing signature validation if a signing key (`KeyDescriptor`) is included.<li>`validateAssertionSignature` indicates whether the SAML assertions from the identity provider  are cryptographically signed. A `null` value indicates that this setting is derived from  the SAML metadata from the identity provider performing signature validation if a signing key (`KeyDescriptor`) is included.</li><li>`identityProviderMetadataXml` is the metadata of the identity provider.</li></ul>
      properties:
        emailAttributeName:
          type: string
        entityId:
          type: string
        firstNameAttributeName:
          type: string
        groupsAttributeName:
          type: string
        identityProviderName:
          type: string
        lastNameAttributeName:
          type: string
        usernameAttributeName:
          type: string
        validateAssertionSignature:
          type: boolean
        validateResponseSignature:
          type: boolean
      type: object
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
